[build]
  publish = "dist"
  command = "pnpm install --frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  COREPACK_ENABLE = "0"

[[plugins]]
  package = "@netlify/plugin-pnpm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
