[build]
  publish = "dist"
  command = "rm -rf .netlify .cache node_modules/.cache && pnpm install --frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
