name: Bandit Security Scan

on:
  workflow_dispatch:
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bandit
      run: pip install bandit==1.7.5

    - name: Run Bandit
      run: bandit --exit-zero -f json -o bandit_report.json .

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v2
      with:
        name: bandit_report
        path: bandit_report.json
