name: Python Ruff Linter and Auto-Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permission for GITHUB_TOKEN to push changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for pushing changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff and Auto-Fix issues
        id: ruff_fix
        run: ruff check . --fix
        working-directory: ./backend

      - name: Check for changes
        id: git_status
        run: echo "changes=$(git status --porcelain)" >> $GITHUB_OUTPUT
        working-directory: ./backend

      - name: Commit and Push changes if any
        if: steps.git_status.outputs.changes != '' && github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fix Python code style with Ruff"
          git push
        working-directory: ./backend
